services:
  # Auth Microservice - Core Authentication
  - type: web
    name: mediflow-auth
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.auth
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        value: mediFlowSecureSecretKeyForProductionDeploymentWithSufficientLengthForHS512Algorithm2024
      - key: JWT_EXPIRATION
        value: 900000
      - key: DATABASE_URL
        fromDatabase:
          name: mediflow-database
          property: connectionString

  # Drugs Microservice - Inventory Management
  - type: web
    name: mediflow-drugs
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.drugs
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AUTH_SERVICE_URL
        value: https://mediflow-auth.onrender.com
      - key: JWT_SECRET
        value: mediFlowSecureSecretKeyForProductionDeploymentWithSufficientLengthForHS512Algorithm2024
      - key: JWT_EXPIRATION
        value: 900000
      - key: DATABASE_URL
        fromDatabase:
          name: mediflow-database
          property: connectionString

  # Subscription Microservice - Subscription Management
  - type: web
    name: mediflow-subscriptions
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.subscription
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AUTH_SERVICE_URL
        value: https://mediflow-auth.onrender.com
      - key: DRUGS_SERVICE_URL
        value: https://mediflow-drugs.onrender.com
      - key: JWT_SECRET
        value: mediFlowSecureSecretKeyForProductionDeploymentWithSufficientLengthForHS512Algorithm2024
      - key: JWT_EXPIRATION
        value: 900000
      - key: DATABASE_URL
        fromDatabase:
          name: mediflow-database
          property: connectionString

  # Refill Microservice - Order Processing
  - type: web
    name: mediflow-refills
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.refill
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AUTH_SERVICE_URL
        value: https://mediflow-auth.onrender.com
      - key: SUBSCRIPTION_SERVICE_URL
        value: https://mediflow-subscriptions.onrender.com
      - key: JWT_SECRET
        value: mediFlowSecureSecretKeyForProductionDeploymentWithSufficientLengthForHS512Algorithm2024
      - key: JWT_EXPIRATION
        value: 900000
      - key: DATABASE_URL
        fromDatabase:
          name: mediflow-database
          property: connectionString

  # Swagger Aggregator - API Documentation
  - type: web
    name: mediflow-swagger
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.swagger
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AUTH_SERVICE_URL
        value: https://mediflow-auth.onrender.com
      - key: DRUGS_SERVICE_URL
        value: https://mediflow-drugs.onrender.com
      - key: SUBSCRIPTION_SERVICE_URL
        value: https://mediflow-subscriptions.onrender.com
      - key: REFILL_SERVICE_URL
        value: https://mediflow-refills.onrender.com
