services:
  # PostgreSQL Database
  - type: pserv
    name: pharmacy-db
    plan: free
    runtime: docker

  # Auth Microservice
  - type: web
    name: auth-microservice
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.auth
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        value: pharmacySecretKeyForJWTTokenGenerationOnRender2024
      - key: JWT_EXPIRATION
        value: 900000
      - key: DATABASE_URL
        fromDatabase:
          name: pharmacy-db
          property: connectionString

  # Drugs Microservice
  - type: web
    name: drugs-microservice
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.drugs
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AUTH_SERVICE_URL
        value: https://auth-microservice.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: pharmacy-db
          property: connectionString

  # Subscription Microservice
  - type: web
    name: subscription-microservice
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.subscription
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AUTH_SERVICE_URL
        value: https://auth-microservice.onrender.com
      - key: DRUGS_SERVICE_URL
        value: https://drugs-microservice.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: pharmacy-db
          property: connectionString

  # Refill Microservice
  - type: web
    name: refill-microservice
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.refill
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AUTH_SERVICE_URL
        value: https://auth-microservice.onrender.com
      - key: SUBSCRIPTION_SERVICE_URL
        value: https://subscription-microservice.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: pharmacy-db
          property: connectionString

  # Swagger Aggregator
  - type: web
    name: swagger-aggregator
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.swagger
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: AUTH_SERVICE_URL
        value: https://auth-microservice.onrender.com
      - key: DRUGS_SERVICE_URL
        value: https://drugs-microservice.onrender.com
      - key: SUBSCRIPTION_SERVICE_URL
        value: https://subscription-microservice.onrender.com
      - key: REFILL_SERVICE_URL
        value: https://refill-microservice.onrender.com
