server:
  port: 8081

spring:
  application:
    name: drugs-microservice
  datasource:
    url: jdbc:h2:file:./data/drugs-pharmacy
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: pharmacySecretKeyForJWTTokenGenerationWithSufficientLengthForHS512Algorithm2024
  expiration: 900000

logging:
  level:
    com.pharmacy.drugs: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: cloud
  datasource:
    url: jdbc:h2:mem:drugs-pharmacy
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
