server:
  port: ${PORT:8085}

spring:
  profiles:
    active: prod

services:
  auth:
    url: ${AUTH_SERVICE_URL}
  drugs:
    url: ${DRUGS_SERVICE_URL}
  subscription:
    url: ${SUBSCRIPTION_SERVICE_URL}
  refill:
    url: ${REFILL_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.pharmacy: INFO
