server:
  port: 8083

spring:
  application:
    name: refill-microservice
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

jwt:
  secret: pharmacySecretKeyForJWTTokenGenerationWithSufficientLengthForHS512Algorithm2024OnRender
  expiration: 900000

# External service URLs
subscription:
  service:
    url: http://localhost:8082

drugs:
  service:
    url: http://localhost:8081

logging:
  level:
    com.pharmacy.refill: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

# External service URLs
subscription:
  service:
    url: http://localhost:8082

drugs:
  service:
    url: http://localhost:8081

---
spring:
  config:
    activate:
      on-profile: cloud
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
